In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Vaini,TO,2021-11-23 03:29:21,-21.2000,-175.2000,84.36,79,40,5.75
1,1,Cape Town,ZA,2021-11-23 03:30:03,-33.9258,18.4232,63.10,70,0,19.57
2,2,New Norfolk,AU,2021-11-23 03:34:14,-42.7826,147.0587,74.91,40,100,1.99
3,3,Yellowknife,CA,2021-11-23 03:31:18,62.4560,-114.3525,-8.59,77,40,3.00
4,4,Mongo,TD,2021-11-23 03:34:14,12.1844,18.6930,74.98,24,100,4.63

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
temps

[84.36,
 63.1,
 74.91,
 0,
 74.98,
 85.95,
 27.81,
 69.75,
 61.68,
 33.1,
 0,
 57.25,
 0,
 38.05,
 0,
 62.89,
 28.92,
 75.27,
 75.56,
 71.15,
 16.03,
 32.43,
 0,
 75.9,
 17.11,
 21.51,
 40.28,
 82.26,
 80.58,
 80.1,
 87.24,
 31.24,
 56.32,
 61.97,
 40.91,
 85.82,
 77.38,
 70.05,
 77.74,
 73.13,
 39.31,
 20.55,
 20.77,
 64.56,
 0,
 3.0,
 77.07,
 31.91,
 72.77,
 53.83,
 22.98,
 77.25,
 69.98,
 13.98,
 20.52,
 73.87,
 33.39,
 70.57,
 33.82,
 63.55,
 75.81,
 42.42,
 0,
 20.86,
 28.92,
 0,
 88.3,
 80.69,
 9.99,
 59.4,
 83.35,
 52.83,
 27.99,
 82.65,
 80.19,
 51.28,
 77.43,
 17.33,
 69.39,
 3.15,
 56.39,
 64.62,
 0,
 81.34,
 0,
 37.29,
 85.93,
 0,
 26.76,
 17.62,
 77.95,
 7.14,
 68.02,
 44.87,
 62.44,
 83.05,
 66.83,
 65.52,
 73.8,
 54.63,
 0,
 48.15,
 46.2,
 84.18,
 34.05,
 16.43,
 60.84,
 39.67,
 1.24,
 70.59,
 54.0,
 8.71,
 68.7,
 45.93,
 51.8,
 40.42,
 77.09,
 45.79,
 53.26,
 19.6,
 26.85,
 19.78,
 52.83,
 45.0,
 82.92,
 0,
 61.86,
 68.58,
 84.83,
 78.03,
 73.92,
 65.89,
 77.34,
 43.0,
 91.45,
 31.39,
 71.82,
 34.05,
 70.77,
 0,
 77.05,
 69.08,
 73.33,
 70.03,
 0,
 65.55,
 69.62,
 9.14,
 23.22,
 29.98,
 12.42,
 69.21,
 65.91,
 46.38,
 80.08,
 64.83,
 92.97,
 63.21,
 60.71,
 80.8,
 83.8,
 57.78,
 65.34,
 85.87,
 2.28,
 58.89,
 44.26,
 61.77,
 0,
 46.83,
 49.53,
 0,
 58.73,
 62.51,
 84.0,
 68.52,
 77.22,
 71.62,
 20.5,
 80.15,
 66.18,
 55.83,
 71.74,
 81.12,
 0,
 69.46,
 75.16,
 75.13,
 67.68,
 42.26,
 65.62,
 89.4,
 61.72,
 75.18,
 39.18,
 78.84,
 72.61,
 71.08,
 72.82,
 57.09,
 37.18,
 78.89,
 34.0,
 87.08,
 77.99,
 38.26,
 59.76,
 39.02,
 59.23,
 1.6,
 52.02,
 45.61,
 71.4,
 25.02,
 52.03,
 29.93,
 73.89,
 65.01,
 49.71,
 64.31,
 25.09,
 79.41,
 73.33,
 32.86,
 30.47,
 84.15,
 0,
 78.1,
 68.5,
 82.47,
 78.75,
 76.44,
 48.43,
 58.3,
 37.0,
 25.2,
 14.07,
 46.69,
 84.09,
 36.05,
 18.55,
 80.74,
 74.08,
 38.19,
 50.81,
 37.35,
 26.28,
 75.94,
 51.66,
 83.46,
 82.49,
 24.91,
 76.24,
 75.04,
 87.91,
 71.33,
 56.17,
 13.69,
 72.73,
 75.72,
 53.71,
 77.36,
 22.62,
 90.59,
 36.91,
 81.45,
 40.08,
 36.79,
 78.37,
 81.09,
 46.51,
 27.52,
 80.01,
 0,
 82.44,
 75.22,
 46.85,
 60.49,
 78.76,
 31.87,
 62.82,
 26.62,
 16.84,
 49.93,
 65.53,
 38.1,
 70.25,
 28.63,
 58.15,
 75.63,
 89.38,
 83.62,
 47.52,
 49.93,
 1.58,
 84.22,
 80.22,
 5.07,
 44.78,
 63.25,
 80.1,
 48.09,
 0,
 55.76,
 76.32,
 65.86,
 36.21,
 67.71,
 14.61,
 0,
 25.07,
 65.14,
 87.94,
 0,
 57.09,
 58.05,
 61.12,
 43.52,
 76.73,
 22.68,
 73.02,
 86.16,
 80.44,
 0,
 51.12,
 29.39,
 36.9,
 13.78,
 82.81,
 62.31,
 89.91,
 65.37,
 40.91,
 84.96,
 77.68,
 83.73,
 80.33,
 76.73,
 23.97,
 20.64,
 82.13,
 81.39,
 45.7,
 34.48,
 15.91,
 77.18,
 50.63,
 78.33,
 42.98,
 72.34,
 44.6,
 78.35,
 70.79,
 55.87,
 51.78,
 63.7,
 35.17,
 64.11,
 65.77,
 76.71,
 73.35,
 25.88,
 71.74,
 82.53,
 42.96,
 40.42,
 82.33,
 45.81,
 57.67,
 75.16,
 59.04,
 62.42,
 32.83,
 70.21,
 35.04,
 15.24,
 30.83,
 29.32,
 18.55,
 39.29,
 74.19,
 71.02,
 52.36,
 33.22,
 68.67,
 27.48,
 12.06,
 46.87,
 53.69,
 87.42,
 82.42,
 17.85,
 66.25,
 68.54,
 82.87,
 63.34,
 44.65,
 40.55,
 76.51,
 69.35,
 82.22,
 66.0,
 48.76,
 33.13,
 84.52,
 69.51,
 77.54,
 35.37,
 80.89,
 52.23,
 79.66,
 80.08,
 64.62,
 77.0,
 79.63,
 0,
 56.25,
 45.09,
 63.14,
 62.1,
 82.17,
 52.56,
 39.11,
 47.16,
 78.78,
 69.76,
 16.99,
 38.12,
 69.64,
 57.65,
 39.15,
 56.34,
 59.63,
 37.45,
 14.76,
 18.99,
 49.41,
 71.29,
 10.8,
 82.11,
 35.94,
 12.96,
 78.51,
 79.14,
 80.42,
 34.39,
 29.35,
 39.51,
 76.24,
 80.15,
 39.18,
 28.27,
 29.91,
 81.23,
 74.52,
 7.14,
 66.94,
 45.12,
 0,
 82.72,
 77.13,
 43.16,
 82.38,
 85.75,
 88.11,
 47.35,
 43.68,
 75.99,
 83.89,
 46.51,
 72.23,
 76.14,
 47.55,
 58.86,
 43.16,
 75.88,
 14.22,
 41.31,
 57.51,
 78.58,
 9.21,
 10.99,
 35.17,
 71.62,
 73.71,
 58.68,
 72.37,
 0,
 78.08,
 57.09,
 75.58,
 70.41,
 64.74,
 80.22,
 77.85,
 48.72,
 70.52,
 47.35,
 32.95,
 66.56,
 34.95,
 76.12,
 66.9,
 29.1,
 77.36,
 38.26,
 28.58,
 77.94,
 83.68,
 33.69,
 72.73,
 59.99,
 81.72,
 87.94,
 18.14,
 43.79,
 52.12,
 41.81,
 82.27,
 56.05,
 80.22,
 65.44,
 47.41,
 39.51,
 63.01,
 67.32,
 50.74,
 17.47,
 0,
 61.83,
 14.18,
 43.63,
 59.88,
 84.16,
 69.08,
 76.71,
 79.12,
 25.21,
 62.53,
 26.42,
 69.96,
 72.97,
 62.13,
 86.05,
 48.02,
 29.32,
 55.96,
 33.78,
 25.16,
 76.75,
 15.87,
 0,
 76.84,
 85.33]

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of Windspeed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 80
What is the maximum temperature you would like for your trip? 95

In [20]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Vaini,TO,2021-11-23 03:29:21,-21.2000,-175.2000,84.36,79,40,5.75
5,5,Samarai,PG,2021-11-23 03:34:15,-10.6167,150.6667,85.95,70,18,15.90
27,27,Butaritari,KI,2021-11-23 03:34:22,3.0707,172.7902,82.26,77,20,11.61
28,28,Kapaa,US,2021-11-23 03:34:22,22.0752,-159.3190,80.58,77,90,1.01
29,29,Sao Filipe,CV,2021-11-23 03:34:23,14.8961,-24.4956,80.10,63,0,7.90
30,30,Labuhan,ID,2021-11-23 03:34:23,-6.8844,112.2051,87.24,62,89,4.36
35,35,Dingle,PH,2021-11-23 03:34:25,10.9995,122.6711,85.82,72,67,13.20
66,66,Kloulklubed,PW,2021-11-23 03:35:35,7.0419,134.2556,88.30,77,89,12.88
67,67,Salalah,OM,2021-11-23 03:35:36,17.0151,54.0924,80.69,18,0,10.36
70,70,Bengkulu,ID,2021-11-23 03:35:37,-3.8004,102.2655,83.35,65,90,4.45

In [21]:
preferred_cities_df.count()

City_ID       84
City          84
Country       84
Date          84
Lat           84
Lng           84
Max Temp      84
Humidity      84
Cloudiness    84
Wind Speed    84
dtype: int64

In [22]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng Hotel Name
0         Vaini      TO     84.36 -21.2000 -175.2000
5       Samarai      PG     85.95 -10.6167  150.6667
27   Butaritari      KI     82.26   3.0707  172.7902
28        Kapaa      US     80.58  22.0752 -159.3190
29   Sao Filipe      CV     80.10  14.8961  -24.4956
30      Labuhan      ID     87.24  -6.8844  112.2051
35       Dingle      PH     85.82  10.9995  122.6711
66  Kloulklubed      PW     88.30   7.0419  134.2556
67      Salalah      OM     80.69  17.0151   54.0924
70     Bengkulu      ID     83.35  -3.8004  102.2655

In [23]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [24]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.

In [25]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [27]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [28]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))